_target_: aics_im2im.models.im2im.GAN

save_images_every_n_epochs: 1
save_dir: ${paths.output_dir}

x_key: ${source_col}
patch_shape:

backbone:
  _target_: monai.networks.nets.DynUNet
  spatial_dims: ${spatial_dims}
  in_channels: ${raw_im_channels}
  out_channels: 1
  strides: [1, 2, 2, 2,2]
  kernel_size: [3, 3, 3, 3,3]
  upsample_kernel_size: [2, 2, 2,2]
  dropout: 0.0
  res_block: True

task_heads: ${kv_to_dict:${model._aux._tasks}}

discriminator:
  _target_: aics_im2im.nn.discriminator.MultiScaleDiscriminator
  n_scales: 1
  input_nc: 2
  n_layers: 3

optimizer:
  generator:
    _partial_: True
    _target_: torch.optim.Adam
    lr: 0.0001
    weight_decay: 0.0001
    betas: [0.5, 0.999]
  discriminator:
    _partial_: True
    _target_: torch.optim.Adam
    lr: 0.0001
    weight_decay: 0.0001
    betas: [0.5, 0.999]


lr_scheduler:
  generator:
    _partial_: True
    _target_: torch.optim.lr_scheduler.ExponentialLR
    gamma: 0.995
  discriminator:
    _partial_: True
    _target_: torch.optim.lr_scheduler.ExponentialLR
    gamma: 0.995

inference_args:
  sw_batch_size: 1
  roi_size: ${model.patch_shape}

_aux:
  _tasks:
    - - ${target_col}
      - _target_: aics_im2im.nn.aux_head.GANHead
        gan_loss:
          _target_: aics_im2im.nn.losses.gan_loss.pix2pix_hd
          scales: 1
        reconstruction_loss:
          _target_: torch.nn.MSELoss
        save_raw: True
