_target_: cyto_dl.models.im2im.GAN

save_images_every_n_epochs: 1
save_dir: ${paths.output_dir}

x_key: ${source_col}

backbone:
  _target_: monai.networks.nets.DynUNet
  spatial_dims: ${spatial_dims}
  in_channels: ${raw_im_channels}
  out_channels: 1
  strides: [1, 2, 2]
  kernel_size: [3, 3, 3]
  upsample_kernel_size: [2, 2]
  filters: [16, 32, 64]
  dropout: 0.0
  res_block: True

task_heads: ${kv_to_dict:${model._aux._tasks}}

discriminator:
  _target_: cyto_dl.nn.discriminators.MultiScaleDiscriminator
  n_scales: 1
  input_nc: 2 #conditioning image+real/fake image
  n_layers: 1
  ndf: 16 #number of filters per layer
  dim: ${spatial_dims}

optimizer:
  generator:
    _partial_: True
    _target_: torch.optim.Adam
    lr: 0.0001
    weight_decay: 0.0001
    betas: [0.5, 0.999]
  discriminator:
    _partial_: True
    _target_: torch.optim.Adam
    lr: 0.0001
    weight_decay: 0.0001
    betas: [0.5, 0.999]

lr_scheduler:
  generator:
    _partial_: True
    _target_: torch.optim.lr_scheduler.ExponentialLR
    gamma: 0.998
  discriminator:
    _partial_: True
    _target_: torch.optim.lr_scheduler.ExponentialLR
    gamma: 0.998

inference_args:
  sw_batch_size: 1
  roi_size: ${data._aux.patch_shape}
  overlap: 0
  progress: True
  mode: "gaussian"

_aux:
  _tasks:
    - - ${target_col}
      - _target_: cyto_dl.nn.GANHead_resize
        gan_loss:
          _target_: cyto_dl.nn.losses.Pix2PixHD
          scales: 1
        reconstruction_loss:
          _target_: torch.nn.MSELoss
        postprocess:
          input:
            _target_: cyto_dl.models.im2im.utils.postprocessing.ActThreshLabel
            rescale_dtype: numpy.uint8
          prediction:
            _target_: cyto_dl.models.im2im.utils.postprocessing.ActThreshLabel
            rescale_dtype: numpy.uint8
        in_channels: 1
        out_channels: 1
        upsample_ratio: 4
        resolution: hr
        upsample_method: nontrainable
