_target_: cyto_dl.models.im2im.MultiTaskIm2Im

save_images_every_n_epochs: 1
x_key: ${source_col}
save_dir: ${paths.output_dir}

backbone:
  _target_: monai.networks.nets.DynUNet
  spatial_dims: ${spatial_dims}
  in_channels: ${raw_im_channels}
  out_channels: ${eval:${spatial_dims}+3}
  strides: [1, 2, 2]
  kernel_size: [3, 3, 3]
  upsample_kernel_size: [2, 2]
  filters: [16, 32, 64]
  dropout: 0.0
  res_block: True

task_heads: ${kv_to_dict:${model._aux._tasks}}

optimizer:
  generator:
    _partial_: True
    _target_: torch.optim.AdamW
    lr: 0.0001
    weight_decay: 0.001

lr_scheduler:
  generator:
    _partial_: True
    _target_: torch.optim.lr_scheduler.ExponentialLR
    gamma: 0.998

inference_args:
  sw_batch_size: 1
  roi_size: ${data._aux.patch_shape}
  overlap: 0
  progress: True
  mode: "gaussian"

_aux:
  _tasks:
    - - ${target_col}
      - _target_: cyto_dl.nn.BaseHead
        loss:
          _target_: cyto_dl.models.im2im.utils.InstanceSegLoss
          dim: ${spatial_dims}
        postprocess:
          input:
            _target_: cyto_dl.models.im2im.utils.postprocessing.ActThreshLabel
            dtype: numpy.float32
          prediction:
            _target_: cyto_dl.models.im2im.utils.instance_seg.InstanceSegCluster
            dim: ${spatial_dims}
            min_size: 100
