_target_: cyto_dl.models.im2im.MultiTaskIm2Im

save_images_every_n_epochs: 1
save_dir: ${paths.output_dir}

x_key: ${source_col}

backbone:
  _target_: cyto_dl.nn.vits.MAE
  spatial_dims: ${spatial_dims}
  # base_patch_size* num_patches should be your patch shape
  base_patch_size: [4, 32, 32]
  num_patches: [4, 16, 16]
  emb_dim: 256
  encoder_layer: 8
  encoder_head: 4
  decoder_layer: 1
  use_crossmae: True
task_heads: ${kv_to_dict:${model._aux._tasks}}

optimizer:
  generator:
    _partial_: True
    _target_: torch.optim.AdamW
    weight_decay: 0.05

lr_scheduler:
  generator:
    _partial_: True
    _target_: torch.optim.lr_scheduler.OneCycleLR
    max_lr: 0.0001
    epochs: ${trainer.max_epochs}
    steps_per_epoch: 1
    pct_start: 0.01

inference_args:
  sw_batch_size: 1
  roi_size: ${data._aux.patch_shape}
  overlap: 0
  progress: True
  mode: "gaussian"

_aux:
  _tasks:
    - - ${source_col}
      - _target_: cyto_dl.nn.head.mae_head.MAEHead
        loss:
        postprocess:
          input:
            _target_: cyto_dl.models.im2im.utils.postprocessing.ActThreshLabel
            rescale_dtype: numpy.uint8
          prediction:
            _target_: cyto_dl.models.im2im.utils.postprocessing.ActThreshLabel
            rescale_dtype: numpy.uint8
