_target_: aics_im2im.models.im2im.MultiTaskIm2Im

save_images_every_n_epochs: 10
save_dir: ${paths.output_dir}
x_key: ${source_col}
patch_shape:

backbone:
  _target_: monai.networks.nets.DynUNet
  spatial_dims: 3
  in_channels: 1
  out_channels: 1
  strides: [1, 2, 2, 2, 2]
  kernel_size: [3, 3, 3, 3, 3]
  upsample_kernel_size: [2, 2, 2, 2]
  filters: [32, 64, 128, 256, 512]
  dropout: 0.1
  res_block: True

tasks:
  seg:
    head:
      _target_: aics_im2im.nn.IdentityAuxHead
      # _target_: aics_im2im.nn.AuxHead
      # resolution: lr
      # in_channels: 32
      # out_channels: 1
      # spatial_dims: 3
      # n_convs: 3
      # dropout: 0.1
      # final_act:
      #   _target_: torch.nn.Identity
      # first_layer:
      #   _target_: torch.nn.Identity

    loss:
      _target_: monai.losses.DiceFocalLoss
      sigmoid: True

optimizer:
  generator:
    _partial_: True
    _target_: torch.optim.Adam
    lr: 0.0003
    weight_decay: 0.0001

lr_scheduler:
  generator:
    _partial_: True
    _target_: torch.optim.lr_scheduler.ExponentialLR
    gamma: 0.99

postprocessing:
  input:
    raw:
      _target_: aics_im2im.models.im2im.utils.postprocessing.rescale
      _partial_: True
    seg:
      _target_: aics_im2im.models.im2im.utils.postprocessing.rescale
      _partial_: True
  prediction:
    seg:
      _target_: aics_im2im.models.im2im.utils.postprocessing.sigmoid_rescale
      _partial_: True
