_target_: aics_im2im.models.im2im.MultiTaskIm2Im

save_images_every_n_epochs: 1
x_key: ${source_col}
patch_shape: [32, 512, 512]
save_dir: ${paths.output_dir}

backbone:
  _target_: monai.networks.nets.DynUNet
  spatial_dims: 3
  in_channels: 1
  out_channels: 5
  strides: [1, 2, 2, 2, 2]
  kernel_size: [3, 3, 3, 3, 3]
  upsample_kernel_size: [2, 2, 2, 2]
  filters: [64, 128, 256, 512, 768]
  dropout: 0.0
  res_block: True

task_heads: ${kv_to_dict:${model._aux._tasks}}

optimizer:
  generator:
    _partial_: True
    _target_: torch.optim.AdamW
    lr: 0.0001
    weight_decay: 0.001

lr_scheduler:
  generator:
    _partial_: True
    _target_: torch.optim.lr_scheduler.ExponentialLR
    gamma: 0.998

inference_args:
  sw_batch_size: 1
  roi_size: ${model.patch_shape}

_aux:
  _tasks:
    - - ${target_col}
      - _target_: aics_im2im.nn.BaseAuxHead
        loss:
          _target_: aics_im2im.models.im2im.utils.omnipose.OmniposeLoss
          dim: 3
        postprocess:
          input:
            _target_: aics_im2im.models.im2im.utils.postprocessing.detach
            _partial_: True
          prediction:
            _target_: aics_im2im.models.im2im.utils.postprocessing.detach
            _partial_: True
