_target_: cyto_dl.models.im2im.MultiTaskIm2Im

save_images_every_n_epochs: 1
save_dir: ${paths.output_dir}

x_key: ${source_col}

backbone:
  _target_: monai.networks.nets.DynUNet
  spatial_dims: ${spatial_dims}
  in_channels: ${raw_im_channels}
  out_channels: 1
  strides: [1, 2, 2]
  kernel_size: [3, 3, 3]
  upsample_kernel_size: [2, 2]
  dropout: 0.0
  res_block: True
  filters: ${model._aux.filters}

task_heads:
  target:
    _target_: cyto_dl.nn.head.MaskHead
    mask_key: ${exclude_mask_col}
    loss:
      _target_: monai.losses.MaskedDiceLoss
      sigmoid: True
    postprocess:
      input:
        _target_: cyto_dl.models.im2im.utils.postprocessing.ActThreshLabel
        rescale_dtype: numpy.uint8
      prediction:
        _target_: cyto_dl.models.im2im.utils.postprocessing.AutoThreshold
        method: "threshold_otsu"

    save_input: True

optimizer:
  generator:
    _partial_: True
    _target_: torch.optim.Adam
    lr: 0.0001
    weight_decay: 0.0001

lr_scheduler:
  generator:
    _partial_: True
    _target_: torch.optim.lr_scheduler.ExponentialLR
    gamma: 0.995

inference_args:
  sw_batch_size: 1
  roi_size: ${data._aux.patch_shape}
  overlap: ${model._aux.overlap}
  mode: "gaussian"

_aux:
  filters:
  overlap:
