_target_: aics_im2im.models.im2im.MultiTaskIm2Im

save_images_every_n_epochs: 1
save_dir: ${paths.output_dir}

x_key: ${source_col}
patch_shape:
cmap_col:
backbone:
  _target_: monai.networks.nets.DynUNet
  spatial_dims: 3
  in_channels: 1
  out_channels: 1
  strides: [1, 2, 2, 2, 2]
  kernel_size: [3, 3, 3, 3, 3]
  upsample_kernel_size: [2, 2, 2, 2]
  filters: [64, 128, 256, 512, 768]
  dropout: 0.1
  res_block: True

tasks: ${kv_to_dict:${model._aux._tasks}}

optimizer:
  generator:
    _partial_: True
    _target_: torch.optim.Adam
    lr: 0.0001
    weight_decay: 0.0001

lr_scheduler:
  generator:
    _partial_: True
    _target_: torch.optim.lr_scheduler.ExponentialLR
    gamma: 0.995

postprocessing:
  input: ${kv_to_dict:${model._aux._input_postprocessing}}
  prediction: ${kv_to_dict:${model._aux._prediction_postprocessing}}
_aux:
  _input_postprocessing:
    - - ${source_col}
      - _target_: aics_im2im.models.im2im.utils.postprocessing.rescale
        _partial_: True
    - - ${target_col}
      - _target_: aics_im2im.models.im2im.utils.postprocessing.rescale
        _partial_: True
  _prediction_postprocessing:
    - - ${target_col}
      - _target_: aics_im2im.models.im2im.utils.postprocessing.rescale
        _partial_: True

  _tasks:
    - - ${target_col}
      - head:
          _target_: aics_im2im.nn.IdentityAuxHead
        loss:
          _target_: torch.nn.MSELoss
