_target_: cyto_dl.models.im2im.MultiTaskIm2Im

save_images_every_n_epochs: 1
save_dir: ${paths.output_dir}

x_key: ${source_col}

backbone:
  _target_: cyto_dl.nn.vits.Seg_ViT
  spatial_dims: ${spatial_dims}
  # base_patch_size* num_patches should be your patch shape
  base_patch_size: 2
  num_patches: 8
  emb_dim: 16
  encoder_layer: 2
  encoder_head: 1
  decoder_layer: 1
  mask_ratio: 0.75

task_heads: ${kv_to_dict:${model._aux._tasks}}

optimizer:
  generator:
    _partial_: True
    _target_: torch.optim.AdamW
    weight_decay: 0.05

lr_scheduler:
  generator:
    _partial_: True
    _target_: torch.optim.lr_scheduler.OneCycleLR
    max_lr: 0.001
    epochs: ${trainer.max_epochs}
    steps_per_epoch: 1
    pct_start: 0.1

inference_args:
  sw_batch_size: 1
  roi_size: ${data._aux.patch_shape}
  overlap: 0.25
  mode: "gaussian"

_aux:
  _tasks:
    - - ${target_col}
      - _target_: cyto_dl.nn.BaseHead
        loss:
          _target_: cyto_dl.models.im2im.utils.InstanceSegLoss
          dim: ${spatial_dims}
        save_input: True
        postprocess:
          input:
            _target_: cyto_dl.models.im2im.utils.postprocessing.ActThreshLabel
            dtype: numpy.float32
          prediction:
            _target_: cyto_dl.models.im2im.utils.instance_seg.InstanceSegCluster
            dim: ${spatial_dims}
            min_size: 100
