_target_: cyto_dl.models.classification.Classifier
model:
  _target_: torchvision.models.efficientnet_v2_s
  pretrained: False
  num_classes: 12 # classifying each timepoint as one of four classes
   #4 # 3 for 3 for normal/breakdown/formation classes + 1 indexing
  # only need this if window size != 3
  # _target_: cyto_dl.nn.flexible_torchvision.FlexibleTorchvision
  # in_channels: 3
  # torchvision_model:
  #   _target_: torchvision.models.resnet18
  #   pretrained: False
  #   num_classes: 3
x_key: 'img'
save_dir: ${paths.output_dir}
save_images_every_n_epochs: 10


optimizer:
  _partial_: True
  _target_: torch.optim.AdamW
  lr: 0.03
  weight_decay: 0.01

lr_scheduler:
  _partial_: True
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.995