
help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

clean: ## Clean autogenerated files
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage

clean-logs: ## Clean logs
	rm -rf logs/**

format: ## Run pre-commit hooks
	pre-commit run -a

test: ## Run not slow tests
	pytest -k "not slow"

test-full: ## Run all tests
	pytest

sync-reqs-files:
	pdm export -f requirements --without-hashes -o requirements/requirements.txt
	pdm export -f requirements -G equiv --no-default --without-hashes -o requirements/equiv-requirements.txt
	pdm export -f requirements -G spharm --no-default --without-hashes -o requirements/spharm-requirements.txt
	pdm export -f requirements -G omnipose --no-default --without-hashes -o requirements/omnipose-requirements.txt
	pdm export -f requirements -G test --no-default --without-hashes -o requirements/test-requirements.txt
	pdm export -f requirements -G all --without-hashes -o requirements/all-requirements.txt
