defaults:
  - private/pcloud_encoders@encoder.pcloud: equiv.yaml
  - private/pcloud_decoders@decoder.pcloud: foldingnet.yaml
  - private/priors@prior.pcloud: gaussian.yaml
  - private/reconstruction_loss@reconstruction_loss.pcloud: chamfer.yaml

_target_: cyto_dl.models.vae.PointCloudVAE

x_label: pcloud
occupancy_label: 

latent_dim: 100
scale: 2
num_output_points: 2048

encoder:
  pcloud:
    num_features: ${eval:${model.latent_dim}*${model.scale}}

decoder:
  pcloud:
    input_dim: ${eval:${model.latent_dim}*${model.scale}}
    num_output_points: ${model.num_output_points}

prior:
  pcloud:
    dimensionality: ${model.latent_dim}

beta: 1.0

get_rotation: false

optimizer:
  _partial_: true
  _target_: torch.optim.adam.Adam
  lr: 0.0002

