defaults:
  - private/pcloud_encoders@encoder.inputs: equiv.yaml
  - private/pcloud_decoders@decoder.inputs: foldingnet_sphere.yaml
  - private/priors@prior.inputs: identity.yaml
  - private/reconstruction_loss@reconstruction_loss.inputs: chamfer.yaml

_target_: cyto_dl.models.vae.PointCloudVAE

x_label: inputs
occupancy_label: 

latent_dim: 128
scale: 1
num_output_points: 2048
hidden_conv1_dim: 512

encoder:
  inputs:
    num_features: ${eval:${model.latent_dim}*${model.scale}}
    hidden_conv1d_channels: [512, 128]
    x_label: ${model.x_label}

decoder:
  inputs:
    input_dim: ${model.latent_dim}
    num_output_points: ${model.num_output_points}

prior:
  inputs:
    dimensionality: ${model.latent_dim}

beta: 1.0

get_rotation: true

optimizer:
  _partial_: true
  _target_: torch.optim.adam.Adam
  lr: 0.0002

