defaults:
  - private/pcloud_encoders@encoder.pcloud: equiv.yaml
  - private/tabular_encoders@encoder.shcoeff: mlp.yaml
  - private/tabular_encoders@condition_encoder.pcloud: mlp.yaml
  - private/tabular_encoders@condition_decoder.pcloud: mlp.yaml
  - private/pcloud_decoders@decoder.pcloud: foldingnet_sphere.yaml
  - private/priors@prior.pcloud: gaussian.yaml
  - private/reconstruction_loss@reconstruction_loss.pcloud: chamfer.yaml

_target_: cyto_dl.models.vae.PointCloudVAE

x_label: pcloud
condition_keys: ['shcoeff']
occupancy_label: 

latent_dim: 256
scale: 2
num_output_points: 2048
cond_dim: 289

encoder:
  pcloud:
    num_features: ${model.latent_dim}
    hidden_conv1d_channels: [512, 256]
  
  shcoeff:
    hidden_layers: [256]
    _args_: 
    - ${model.cond_dim}
    - ${model.latent_dim}

condition_encoder:
  pcloud: 
    hidden_layers: [256]
    _args_: 
    - ${eval:${model.latent_dim}*2}
    - ${eval:${model.latent_dim}*${model.scale}}

condition_decoder:
  pcloud: 
    hidden_layers: [256]
    _args_: 
    - ${eval:${model.latent_dim}+${model.cond_dim}}
    - ${model.latent_dim}


decoder:
  pcloud:
    input_dim: ${model.latent_dim}
    num_output_points: ${model.num_output_points}


prior:
  pcloud:
    dimensionality: ${model.latent_dim}

beta: 1.0

get_rotation: true

optimizer:
  _partial_: true
  _target_: torch.optim.adam.Adam
  lr: 0.0002

