_target_: aics_im2im.models.MultiTaskIm2Im

save_images_every_n_epochs: 10
x_key: IM
patch_shape: [32, 512, 512]

size: embedseg
backbone:
  _target_: monai.networks.nets.DynUNet
  spatial_dims: 3
  in_channels: 1
  out_channels: 64
  strides: [[1, 1, 1], [1, 2, 2], [1, 1, 1], [2, 2, 2]]
  kernel_size: [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]
  upsample_kernel_size:  [[1, 2, 2], [1, 1, 1], [2, 2, 2]]
  filters: [64, 128, 192, 256]
  dropout: 0.0
  res_block: True


tasks:
  interphase_seg:
    head:
      _target_: aics_im2im.networks.AuxHead
      resolution: lr
      in_channels: 64
      out_channels: 7
      final_act:
        _target_: torch.nn.Identity

    loss:
      _target_: aics_im2im.utils.embedseg_utils.SpatialEmbLoss_3d
      grid_y: 512
      grid_x: 512
      grid_z: 32
      pixel_y: 1
      pixel_x: 1
      pixel_z: 2.6
      n_sigma: 3
      foreground_weight: 4.5
      use_costmap: False
      instance_key: GT_interphase
      label_key: CL_interphase
      center_key: CE_interphase
  mitotic_seg:
    head:
      _target_: aics_im2im.networks.AuxHead
      resolution: lr
      in_channels: 64
      out_channels: 7
      final_act:
        _target_: torch.nn.Identity
    loss:
      _target_: aics_im2im.utils.embedseg_utils.SpatialEmbLoss_3d
      grid_y: 512
      grid_x: 512
      grid_z: 32
      pixel_y: 1
      pixel_x: 1
      pixel_z: 2.6
      n_sigma: 3
      foreground_weight: 8.5
      use_costmap: False
      instance_key: GT_mitotic
      label_key: CL_mitotic
      center_key: CE_mitotic



optimizer: 
  _partial_: True
  _target_: torch.optim.Adam
  lr: 0.001
  weight_decay: 0.001

lr_scheduler:
  _partial_: True
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.998

postprocessing:
  input:
    interphase_seg:
      _target_: aics_im2im.utils.embedseg_utils.concat_dict
      _partial_: True
      keys: ['GT_interphase']
    mitotic_seg:
      _target_: aics_im2im.utils.embedseg_utils.concat_dict
      _partial_: True
      keys: ['GT_mitotic']
    IM:
      _target_: aics_im2im.utils.embedseg_utils.rescale
      _partial_: True
  prediction:
    interphase_seg:
      _target_: aics_im2im.utils.embedseg_utils.generate_instance_clusters
      _partial_: True
      grid_y: 512
      grid_x: 512
      grid_z: 32
      pixel_y: 1
      pixel_x: 1
      pixel_z: 2.6
      n_sigma: 3
    mitotic_seg:
      _target_: aics_im2im.utils.embedseg_utils.generate_instance_clusters
      _partial_: True
      grid_y: 512
      grid_x: 512
      grid_z: 32
      pixel_y: 1
      pixel_x: 1
      pixel_z: 2.6
      n_sigma: 3




