_target_: aics_im2im.models.MultiTaskIm2Im

save_images_every_n_epochs: 10
x_key: Brightfield
patch_shape: [32, 128, 128]

size: simple_lamin
backbone:
  _target_: monai.networks.nets.DynUNet
  spatial_dims: 3
  in_channels: 1
  out_channels: 32
  strides: [[1, 1, 1], [2, 2, 2], [1, 2, 2], [2, 2, 2], [1,2,2]]
  kernel_size: [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3,3,3]]
  upsample_kernel_size:  [[2, 2, 2], [1, 2, 2], [2, 2, 2], [1,2,2]]
  filters: [32, 64, 128,  256,  512]
  dropout: 0.3
  res_block: True


tasks:
  Lamin:
    head:
      _target_: aics_im2im.networks.AuxHead
      resolution: lr
      in_channels: 32
      out_channels: 1
      dropout: 0.3
      final_act:
        _target_: torch.nn.Identity

    loss:
      _target_: torch.nn.MSELoss




optimizer: 
  _partial_: True
  _target_: torch.optim.Adam
  lr: 0.0001
  weight_decay: 0.001

lr_scheduler:
  _partial_: True
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.996



