_target_: aics_im2im.models.vae.PointCloudVAE

x_label: pcloud
occupancy_label: 
# id_label: cell_id

k: 20
latent_dim: 20
num_points: 256
hidden_dim: 64
hidden_conv2d_channels: [64, 64, 64, 64]
hidden_conv1d_channels: [512, 512]


mode: scalar
scalar_inds: 
get_rotation: false
include_cross: false
include_coords: true
symmetry_breaking_axis: 
generate_grid_feats: False

decoder_type: 'foldingnet'
shape: "plane"

loss_type: 'chamfer'

beta: 1.0
embedding_prior: "identity"

eps: 1e-6

optimizer:
  _partial_: true
  _target_: torch.optim.adam.Adam
  lr: 0.0002
