_target_: cyto_dl.models.vae.PointCloudVAE

x_label: pcloud
# id_label: cell_id

latent_dim: 256
num_points: 2048
hidden_encoder_features: [64, 64, 128, 256, 512]
hidden_decoder_dim: 512
k: 20

mode: scalar
get_rotation: False
include_cross: False
include_coords: true
scalar_inds:

beta: 1.0
embedding_prior: "identity"
shape: "sphere"

eps: 1e-6

optimizer:
  _partial_: true
  _target_: torch.optim.adam.Adam
  lr: 0.0002
