# disable python warnings if they annoy you
ignore_warnings: True

# ask user for tags if none are provided in the config
enforce_tags: True

# pretty print config tree at the start of the run using Rich library
print_config: True
precision:
  _target_: torch.set_float32_matmul_precision
  precision: medium
