_target_: src.models.MultiTaskIm2Im

save_images_every_n_epochs: 10
save_dir : ${paths.output_dir}
x_key: raw
patch_shape: 

backbone:
  _target_: monai.networks.nets.DynUNet
  spatial_dims: 3
  in_channels: 1
  out_channels: 64
  strides: [1,2,2,2,2]
  kernel_size: [3,3,3,3,3]
  upsample_kernel_size:  [2,2,2,2]
  filters: [64, 128, 256, 512, 1024]
  dropout: 0.0
  res_block: True


tasks:
  seg:
    head:
      _target_: src.models.components.AuxHead
      resolution: lr
      in_channels: 64
      out_channels: 1
      spatial_dims: 3
      dropout: 0.1
      n_convs: 3
      final_act:
        _target_: torch.nn.Identity
    loss:
      _target_: src.utils.loss_wrapper.LossWrapper
      loss_fn:
        _target_: monai.losses.DiceCELoss
        sigmoid: True
      channel_weight: [1]
      loss_scale: 1
  mitotic_mask:
    head:
      _target_: src.models.components.AuxHead
      resolution: lr
      in_channels: 64
      out_channels: 1
      spatial_dims: 2
      dropout: 0.1
      n_convs: 3
      final_act:
        _target_: torch.nn.Identity
      first_layer:
        _target_: src.models.components.aux_head.ProjectionLayer
        dim: 2
        pool_size: 32
    loss:
      _target_: src.utils.loss_wrapper.LossWrapper
      loss_fn:
        _target_: monai.losses.DiceCELoss
        sigmoid: True
      channel_weight: [1]
      loss_scale: 1


optimizer: 
  generator:
    _partial_: True
    _target_: torch.optim.Adam
    lr: 0.0003
    weight_decay: 0.0001

lr_scheduler:
  generator:
    _partial_: True
    _target_: torch.optim.lr_scheduler.ExponentialLR
    gamma: 0.95

postprocessing:
  input:
    raw:
      _target_: src.utils.postprocessing.rescale
      _partial_: True
    seg:
      _target_: src.utils.postprocessing.rescale
      _partial_: True
    mitotic_mask:
      _target_: src.utils.postprocessing.rescale
      _partial_: True

  prediction:
    seg:
      _target_: src.utils.postprocessing.sigmoid_rescale
      _partial_: True
    mitotic_mask:
      _target_: src.utils.postprocessing.sigmoid_rescale
      _partial_: True




