_target_: src.models.MultiTaskIm2Im

save_images_every_n_epochs: 10
x_key: low_res
patch_shape: [512, 512]

backbone:
  _target_: monai.networks.nets.DynUNet
  spatial_dims: 2
  in_channels: 1
  out_channels: 32
  strides: [1,2,2,2,2, 2]
  kernel_size: [3,3,3,3,3, 3]
  upsample_kernel_size:  [2,2,2,2, 2]
  filters: [ 32, 64, 128, 256,512, 1024 ]
  dropout: 0.1
  res_block: True


tasks:
  high_res:
    head:
      _target_: src.models.components.AuxHead
      resolution: lr
      in_channels: 32
      out_channels: 1
      spatial_dims: 2
      dropout: 0.1
      final_act:
        _target_: torch.nn.Tanh

    loss:
      _target_: torch.nn.MSELoss

gan_loss:
  _target_: src.utils.gan_loss.GANLoss
  gan_mode: 'vanilla'

optimizer: 
  generator:
    _partial_: True
    _target_: torch.optim.Adam
    lr: 0.0003
    weight_decay: 0.001
  discriminator:
    _partial_: True
    _target_: torch.optim.Adam
    lr: 0.0003
    weight_decay: 0.001
    

lr_scheduler:
  generator:
    _partial_: True
    _target_: torch.optim.lr_scheduler.ExponentialLR
    gamma: 0.97
  discriminator:
    _partial_: True
    _target_: torch.optim.lr_scheduler.ExponentialLR
    gamma: 0.97

postprocessing:
  input:
    lr_lamin:
      _target_: src.utils.postprocessing.rescale
      _partial_: True
    hr_lamin:
      _target_: src.utils.postprocessing.rescale
      _partial_: True
  prediction:
    hr_lamin:
      _target_: src.utils.postprocessing.rescale
      _partial_: True


