_target_: aics_im2im.models.MultiTaskIm2Im

save_images_every_n_epochs: 10
save_dir : ${paths.output_dir}
x_key: ${source_col}
patch_shape: [12, 128, 128]

backbone:
  _target_: monai.networks.nets.DynUNet
  spatial_dims: 3
  in_channels: 1
  out_channels: 32
  strides: [1,1,2,1,2]
  kernel_size: [3,3,3,3,3]
  upsample_kernel_size:  [1,2,1,2]
  filters: [ 32, 64, 128, 256, 512]
  dropout: 0.0
  res_block: True

tasks: ${kv_to_dict:${model._aux._tasks}}

discriminator:
  _target_: aics_im2im.models.components.NLayerDiscriminator
  input_nc: 2
  keys: 
    - ${target_col}
  n_layers: 2


gan_loss:
  _target_: aics_im2im.utils.gan_loss.GANLoss
  gan_mode: 'vanilla'

optimizer: 
  generator:
    _partial_: True
    _target_: torch.optim.Adam
    lr: 0.0003
    weight_decay: 0.000
  discriminator:
    _partial_: True
    _target_: torch.optim.Adam
    lr: 0.0003
    weight_decay: 0.001
    

lr_scheduler:
  generator:
    _partial_: True
    _target_: torch.optim.lr_scheduler.ExponentialLR
    gamma: 0.97
  discriminator:
    _partial_: True
    _target_: torch.optim.lr_scheduler.ExponentialLR
    gamma: 0.97

postprocessing: 
  input: ${kv_to_dict:${model._aux._input_postprocessing}}
  prediction: ${kv_to_dict:${model._aux._prediction_postprocessing}}

_aux:
  _input_postprocessing:
    - - ${source_col}
      - _target_: aics_im2im.utils.postprocessing.rescale
        _partial_: True
    - - ${target_col}
      - _target_: aics_im2im.utils.postprocessing.rescale
        _partial_: True
  _prediction_postprocessing:
    - - ${target_col}
      - _target_: aics_im2im.utils.postprocessing.rescale
        _partial_: True

  _tasks:
    - - ${target_col}
      - head:
          _target_: aics_im2im.models.components.AuxHead
          resolution: lr
          in_channels: 32
          out_channels: 1
          spatial_dims: 3
          dropout: 0.0
          final_act:
            _target_: torch.nn.Tanh
        loss:
          _target_: torch.nn.MSELoss
