_target_: aics_im2im.models.vae.EqImageVAE
encoder:
  _target_: giae.so2.modules.Encoder
  out_dim: 64
  hidden_dim: 128
  pool: true
decoder:
  _target_: giae.so2.modules.Decoder
  input_size: 32
  hidden_size: 128
latent_dim: 32
x_label: image
optimizer:
  _partial_: true
  _target_: torch.optim.adam.Adam
  lr: 0.001
  betas:
    - 0.9
    - 0.999
  eps: 1.0e-08
  weight_decay: 0
  amsgrad: false
beta: 1.0
prior:
  image:
    _target_: aics_im2im.models.vae.priors.IsotropicGaussianPrior
    dimensionality: 32
reconstruction_loss:
  image:
    _target_: torch.nn.modules.loss.MSELoss
    reduction: none
