_target_: src.models.MultiTaskIm2Im

save_images_every_n_epochs: 10
x_key: raw
patch_shape: [512, 512]

size: large
backbone:
  _target_: monai.networks.nets.DynUNet
  spatial_dims: 2
  in_channels: 1
  out_channels: 32
  strides: [1,2,2,2,2, 2]
  kernel_size: [3,3,3,3,3, 3]
  upsample_kernel_size:  [2,2,2,2, 2]
  filters: [ 32, 64, 128, 256,512, 1024 ]
  dropout: 0.1
  res_block: True


tasks:
  seg:
    head:
      _target_: src.models.components.AuxHead
      resolution: lr
      in_channels: 32
      out_channels: 1
      spatial_dims: 2
      dropout: 0.1
      final_act:
        _target_: torch.nn.Identity

    loss:
      _target_: monai.losses.DiceCELoss
      sigmoid: True



optimizer: 
  generator:
    _partial_: True
    _target_: torch.optim.Adam
    lr: 0.001
    weight_decay: 0.001

lr_scheduler:
  generator:
    _partial_: True
    _target_: torch.optim.lr_scheduler.ExponentialLR
    gamma: 0.995

postprocessing:
  input:
    raw:
      _target_: src.utils.embedseg_utils.rescale
      _partial_: True
    seg:
      _target_: src.utils.embedseg_utils.rescale
      _partial_: True
  prediction:
    seg:
      _target_: src.utils.embedseg_utils.sigmoid_rescale
      _partial_: True




