_target_: src.models.MultiTaskIm2Im

save_images_every_n_epochs: 1
save_dir : ${paths.output_dir}
x_key: ${source_col}
patch_shape: 

backbone:
  _target_: monai.networks.nets.DynUNet
  spatial_dims: 3
  in_channels: 1
  out_channels: 16
  strides: [1,2,2,2]
  kernel_size: [3,3,3,3]
  upsample_kernel_size:  [2,2,2]
  filters: [32, 64,128, 256]
  dropout: 0.1
  res_block: True


tasks:
  Lamin:
    head:
      _target_: src.models.components.AuxHead
      resolution: lr
      in_channels: 16
      out_channels: 1
      spatial_dims: 3
      dropout: 0.1
      final_act:
        _target_: torch.nn.Identity

    loss:
      _target_: torch.nn.MSELoss

optimizer: 
  generator:
    _partial_: True
    _target_: torch.optim.Adam
    lr: 0.01
    weight_decay: 0.001

lr_scheduler:
  generator:
    _partial_: True
    _target_: torch.optim.lr_scheduler.ExponentialLR
    gamma: 0.995

postprocessing:
  input:
    Brightfield:
      _target_: src.utils.postprocessing.rescale
      _partial_: True
    Lamin:
      _target_: src.utils.postprocessing.rescale
      _partial_: True
  prediction:
    Lamin:
      _target_: src.utils.postprocessing.rescale
      _partial_: True




