_target_: aics_im2im.models.MultiTaskIm2Im

save_images_every_n_epochs: 1
x_key: ${source_col}
patch_shape: [32, 512, 512]
save_dir: ${paths.output_dir}

backbone:
  _target_: monai.networks.nets.DynUNet
  spatial_dims: 3
  in_channels: 1
  out_channels: 5
  strides: [1,2,2,2,2]
  kernel_size: [3,3,3,3,3]
  upsample_kernel_size:  [2,2,2,2]
  filters: [64, 128, 256, 512, 768]
  dropout: 0.1
  res_block: True


tasks:
  seg:
    head:
      _target_: aics_im2im.models.components.IdentityAuxHead
    loss:
      _target_: aics_im2im.utils.omnipose_utils.OmniposeLoss
      dim: 3

optimizer: 
  generator:
    _partial_: True
    _target_: torch.optim.AdamW
    lr: 0.0001
    weight_decay: 0.001

lr_scheduler:
  generator:
    _partial_: True
    _target_: torch.optim.lr_scheduler.ExponentialLR
    gamma: 0.998


postprocessing: 
  input: 
    seg:
      _target_: aics_im2im.utils.postprocessing.detach
      _partial_: True
    raw:
      _target_: aics_im2im.utils.postprocessing.detach
      _partial_: True
  prediction: 
    seg:
      _target_: aics_im2im.utils.postprocessing.detach
      _partial_: True
    # seg:
    #   _target_: aics_im2im.utils.omnipose_utils.OmniposeClustering
    #   _partial_: True



