model:
  _target_: aics_im2im.models.im2im.MultiTaskim2im
  save_images_every_n_epochs: 10
  x_key: raw
  patch_shape:
  - 48
  - 512
  - 512
  backbone:
    _target_: monai.networks.nets.DynUNet
    spatial_dims: 3
    in_channels: 1
    out_channels: 32
    strides:
    - - 1
      - 1
      - 1
    - - 1
      - 2
      - 2
    - - 1
      - 1
      - 1
    - - 2
      - 2
      - 2
    - - 1
      - 1
      - 1
    kernel_size:
    - - 3
      - 3
      - 3
    - - 3
      - 3
      - 3
    - - 3
      - 3
      - 3
    - - 3
      - 3
      - 3
    - - 3
      - 3
      - 3
    upsample_kernel_size:
    - - 1
      - 2
      - 2
    - - 1
      - 1
      - 1
    - - 2
      - 2
      - 2
    - - 1
      - 1
      - 1
    filters:
    - 32
    - 64
    - 128
    - 256
    - 512
    dropout: 0.5
    res_block: true
  tasks:
    seg:
      head:
        _target_: aics_im2im.networks.AuxHead
        resolution: lr
        in_channels: 32
        out_channels: 3
        dropout: 0.5
        final_act:
          _target_: torch.nn.Softmax
          dim: 1
      loss:
        _target_: monai.losses.GeneralizedDiceLoss
        include_background: false
  optimizer:
    generator:
      _partial_: true
      _target_: torch.optim.Adam
      lr: 0.0001
      weight_decay: 0.01
  lr_scheduler:
    generator:
      _partial_: true
      _target_: torch.optim.lr_scheduler.ExponentialLR
      gamma: 0.995
  postprocessing:
    input:
      raw:
        _target_: aics_im2im.models.im2im.utils.postprocessing.rescale
        _partial_: true
      seg:
        _target_: aics_im2im.models.im2im.utils.postprocessing.rescale
        _partial_: true
    prediction:
      seg:
        _target_: aics_im2im.models.im2im.utils.postprocessing.rescale
        _partial_: true
data:
  _target_: aics_im2im.datamodules.PatchDatamodule
  path: //allen/aics/assay-dev/users/Benji/CurrentProjects/20xBF_to_cellseg/laminseg_separate_interphase_and_mitotic_channel/pred_on_mamabear/raw
  num_workers: 16
  batch_size: 1
  pin_memory: true
  persistent_workers: false

  transforms:
    train:
      _target_: monai.transforms.Compose
      transforms:
      - _target_: monai.transforms.LoadImaged
        keys:
        - raw
        reader:
        - _target_: serotiny.image.io.MonaiBioReader
          reader_args:
            dimension_order_out: CZYX
      - _target_: monai.transforms.ToTensord
        keys:
        - raw
      - _target_: aics_im2im.utils.embedseg_utils.max_project
        keys:
        - raw
    predict:
      _target_: monai.transforms.Compose
      transforms:
      - _target_: monai.transforms.LoadImaged
        keys:
        - raw
        reader:
        - _target_: serotiny.image.io.MonaiBioReader
          reader_args:
            dimension_order_out: CZYX
      - _target_: monai.transforms.ToTensord
        keys:
        - raw
      - _target_: aics_im2im.utils.embedseg_utils.max_project
        keys:
        - raw
    valid:
      _target_: monai.transforms.Compose
      transforms:
      - _target_: monai.transforms.LoadImaged
        keys:
        - raw
        reader:
        - _target_: serotiny.image.io.MonaiBioReader
          reader_args:
            dimension_order_out: CZYX
      - _target_: monai.transforms.ToTensord
        keys:
        - raw
      - _target_: aics_im2im.utils.embedseg_utils.max_project
        keys:
        - raw
trainer:
  _target_: pytorch_lightning.Trainer
  max_epochs: null
  gpus:
  - 0
  enable_checkpointing: true
  logger: []
  callbacks:
    _target_: pytorch_lightning.callbacks.EarlyStopping
    mode: min
    monitor: val_loss
    patience: 1000
  precision: 16
  reload_dataloaders_every_n_epochs: 0
  check_val_every_n_epoch: 10
  log_every_n_steps: 1
mlflow:
  tracking_uri: https://mlflow.a100.int.allencell.org/
  experiment_name: benji_im2im_serotiny_port
  run_name: mitotic_goldilocks_leastaug
  run_id: null
  autolog:
    log_every_n_epoch: 1
    log_models: true
seed: 42
log_level: INFO
logs_root: /tmp/serotiny_logs_${uuid:}
mode: predict