# @package _global_

# to execute this experiment run:
# python train.py experiment=example

defaults:
  - override /datamodule: patch.yaml
  - override /model: multitask.yaml
  - override /callbacks: default.yaml
  - override /trainer: gpu.yaml
  - override /logger: mlflow_im2im.yaml

# all parameters below will be merged with parameters from default configurations set above
# this allows you to overwrite only specified parameters

tags: ["dev"]
seed: 12345

trainer:
  max_epochs: 1000
  check_val_every_n_epoch: 10

callbacks:
  early_stopping:
    monitor: val_loss
  model_checkpoint:
    dirpath: ${paths.output_dir}/ckpts
    monitor: val_loss
    save_top_k: 2
    every_n_epochs: 1
model:
  patch_shape: [32, 256, 256]

source_col: raw
target_col: seg

datamodule:
  path: //allen/aics/assay-dev/users/Benji/CurrentProjects/20xBF_to_cellseg/retrain_caax_semseg
  cache_dir: //allen/aics/assay-dev/users/Benji/CurrentProjects/20xBF_to_cellseg/retrain_caax_semseg/cache
  subsample: 
    train: -1
    test: 1
    valid: -1
  batch_size: 4


logger:
  mlflow_im2im:
    experiment_name: benji_caax_semseg
    run_name: pre_normalized_test