# @package _global_

# to execute this experiment run:
# python train.py experiment=example

defaults:
  - override /datamodule: omnipose.yaml
  - override /model: omnipose.yaml
  - override /callbacks: default.yaml
  - override /trainer: gpu.yaml
  - override /logger: mlflow_im2im.yaml

# all parameters below will be merged with parameters from default configurations set above
# this allows you to overwrite only specified parameters

tags: ["dev"]
seed: 12345

experiment_name: benji_omnipose
run_name: cell_omnipose
source_col: raw
target_col: seg
persist_cache: True
# mode: predict

# ckpt_path:  /allen/aics/assay-dev/users/Benji/CurrentProjects/im2im_dev/aics-im2im/logs/train/runs/benji_omnipose/test/2023-02-10_10-29-08/checkpoints/epoch_103.ckpt
trainer:
  max_epochs: 1000
  check_val_every_n_epoch: 5
  gpus: 1


model:
  # save_dir:  /allen/aics/assay-dev/users/Benji/CurrentProjects/im2im_dev/aics-im2im/logs/train/runs/benji_omnipose/test/2023-02-10_10-29-08/
  patch_shape: [32, 256, 256]


datamodule:
  path: ${paths.data_dir}/cell_omnipose_20x/data/
  cache_dir: ${paths.data_dir}/cell_omnipose_20x/cache
  batch_size: 2
  subsample:
    train: 100
    valid: 10
    test: 0


##### ONLY USE WITH A100s
# extras:
#   precision:
#     _target_: torch.set_float32_matmul_precision
#     precision: medium