# @package _global_

# to execute this experiment run:
# python train.py experiment=example

defaults:
  - override /datamodule: gt_to_im.yaml
  - override /model: intensity_transfer_gan.yaml
  - override /callbacks: default.yaml
  - override /trainer: gpu.yaml
  - override /logger: mlflow.yaml

# all parameters below will be merged with parameters from default configurations set above
# this allows you to overwrite only specified parameters

tags: ["dev"]
seed: 12345
experiment_name: benji_synthetic_lamin_from_gt
run_name: pix2pix_hd_mmv_train_loop
persist_cache: True
source_col: seg
target_col: raw

trainer:
  max_epochs: 1000
  check_val_every_n_epoch: 10
  precision: 32

model:
  patch_shape: [32, 128, 128]

datamodule:
  path: ${paths.data_dir}/gt_to_im
  cache_dir: ${paths.data_dir}/gt_to_im/cache
  subsample: 
    train: 100
    test: 1
    valid: 100
  batch_size: 1
  num_workers: 4