# @package _global_

defaults:
  - _self_
  - data: null # choose datamodule with `test_dataloader()` for evaluation
  - model: null
  # only here so that we can use experiments that try to override these
  - logger: null
  - optional callbacks: null
  - trainer: default.yaml
  ########################################################################
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml
  - optional local: default.yaml
  - optional experiment: null

task_name: "compile"
experiment_name: "catchall_experiment"
run_name: "catchall_run"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path:
model_file:
handler_file:
export_path:

#return:
#  mode: network
#

return:
  mode: path
  path: /tmp
