_target_: serotiny.datamodules.dataframe.DataframeDatamodule

path: 
cache_dir: 

num_workers: 8
batch_size: 1
pin_memory: True
persistent_workers: False
split_column: split
columns: 
  - raw
  - seg 
  - split

transforms:
  train:
    _target_: monai.transforms.Compose
    transforms: 
      - _target_: monai.transforms.LoadImaged
        keys: ['raw', 'seg'] 
        reader:
        - _target_: serotiny.image.io.MonaiBioReader
          dimension_order_out: 'CZYX'

      - _target_: monai.transforms.ToTensord
        keys: ['raw', 'seg'] 
    
      - _target_: monai.transforms.NormalizeIntensityd
        keys: ['raw']
      
      #creates two new images - CL is a binary segmentation of 'seg'
      # and CE is a boolean image of the object centroids
      - _target_: aics_im2im.utils.EmbedSegPreprocess
        input_key: 'seg'
        output_key:
          class: CL
          centroid: 'CE'

      - _target_: serotiny.image.transforms.RandomMultiScaleCropd
        keys: ['raw', 'seg', 'CL', 'CE']
        patch_shape: ${model.patch_shape}
        patch_per_image: 1
        scales_dict:
          1: ['raw', 'seg', 'CL', 'CE']
        selection_fn:
          _target_: serotiny.image.transforms.bright_sampler.BrightSampler
          key: CE
          threshold: 0
          base_prob: 0

      - _target_: aics_im2im.utils.EmbedSegConcatLabelsd
        input_keys: ['seg', 'CE', 'CL']
        output_key: GT

  test:
    _target_: monai.transforms.Compose
    transforms: 
      - _target_: monai.transforms.LoadImaged
        keys: ['raw'] 
        reader:
        - _target_: serotiny.image.io.MonaiBioReader
          dimension_order_out: 'CZYX'

      - _target_: monai.transforms.ToTensord
        keys: ['raw'] 
    
      - _target_: monai.transforms.NormalizeIntensityd
        keys: ['raw']

  valid:
    _target_: monai.transforms.Compose
    transforms: 
      - _target_: monai.transforms.LoadImaged
        keys: ['raw', 'seg'] 
        reader:
        - _target_: serotiny.image.io.MonaiBioReader
          dimension_order_out: 'CZYX'

      - _target_: monai.transforms.ToTensord
        keys: ['raw', 'seg'] 
    
      - _target_: monai.transforms.NormalizeIntensityd
        keys: ['raw']
      
      - _target_: aics_im2im.utils.EmbedSegPreprocess
        input_key: 'seg'
        output_key:
          class: CL
          centroid: 'CE'

      - _target_: serotiny.image.transforms.RandomMultiScaleCropd
        keys: ['raw', 'seg', 'CL', 'CE']
        patch_shape: ${model.patch_shape}
        patch_per_image: 1
        scales_dict:
          1: ['raw', 'seg', 'CL', 'CE']
        selection_fn:
          _target_: serotiny.image.transforms.bright_sampler.BrightSampler
          key: CE
          threshold: 0
          base_prob: 0

      - _target_: aics_im2im.utils.EmbedSegConcatLabelsd
        input_keys: ['seg', 'CE', 'CL']
        output_key: GT
        
