_target_: serotiny.datamodules.dataframe.DataframeDatamodule

path: 
cache_dir: 

num_workers: 8
batch_size: 1
pin_memory: True
persistent_workers: False
columns: 
  - source

transforms:
  predict:
    _target_: monai.transforms.Compose
    transforms: 
      - _target_: monai.transforms.LoadImaged
        keys: ['source'] 
        reader:
        - _target_: serotiny.image.io.MonaiBioReader
          dimension_order_out: 'CZYX'

      - _target_: monai.transforms.ToTensord
        keys: ['source'] 

      - _target_: aics_im2im.utils.MeanNormalizeIntensity
        keys: ['source']
        lower_bound: 2.5
        upper_bound: 5.0
    
      
