_target_: serotiny.datamodules.dataframe.DataframeDatamodule

path: 
cache_dir: 

num_workers: 8
batch_size: 1
pin_memory: True
persistent_workers: False
columns: 
  - source
  - target

transforms:
  train:
    _target_: monai.transforms.Compose
    transforms: 
      - _target_: monai.transforms.LoadImaged
        keys: ['source', 'target'] 
        reader:
        - _target_: serotiny.image.io.MonaiBioReader
          dimension_order_out: 'CZYX'

      - _target_: monai.transforms.ToTensord
        keys: ['source', 'target'] 

      - _target_: aics_im2im.utils.MatchHistogramToReference
        keys: ['source']
        reference: '/allen/aics/assay-dev/computational/data/nucleus_tracking/lamin/bf'
        sample_size: 10

      - _target_: monai.transforms.RandAdjustContrastd
        keys: ['source']
        prob: 0.25
        gamma: 0.75
    
      - _target_: aics_im2im.utils.MeanNormalizeIntensity
        keys: ['source']
        lower_bound: 5
        upper_bound: 12.0

      - _target_: serotiny.image.transforms.RandomMultiScaleCropd
        keys: ['source', 'target']
        patch_shape: ${model.patch_shape}
        patch_per_image: 1
        scales_dict:
          1: ['source', 'target']
      
      - _target_: aics_im2im.utils.ExtractCentroidd
        input_key: 'target'
        output_key: 'CE'

      - _target_: aics_im2im.utils.EmbedSegConcatLabelsd
        input_keys: ['target', 'CE']
        output_key: GT


  test:
    _target_: monai.transforms.Compose
    transforms: 
      - _target_: monai.transforms.LoadImaged
        keys: ['source', 'target'] 
        reader:
        - _target_: serotiny.image.io.MonaiBioReader
          dimension_order_out: 'CZYX'

      - _target_: monai.transforms.ToTensord
        keys: ['source', 'target'] 

      - _target_: aics_im2im.utils.MatchHistogramToReference
        keys: ['source']
        reference: '/allen/aics/assay-dev/computational/data/nucleus_tracking/lamin/bf'
        sample_size: 10

      - _target_: monai.transforms.RandAdjustContrastd
        keys: ['source']
        prob: 0.25
        gamma: 0.75

      - _target_: aics_im2im.utils.MeanNormalizeIntensity
        keys: ['source']
        lower_bound: 5
        upper_bound: 12.0
      
      - _target_: aics_im2im.utils.ExtractCentroidd
        input_key: 'target'
        output_key: 'CE'

      - _target_: aics_im2im.utils.EmbedSegConcatLabelsd
        input_keys: ['target', 'CE']
        output_key: GT


  valid:
    _target_: monai.transforms.Compose
    transforms: 
      - _target_: monai.transforms.LoadImaged
        keys: ['source', 'target'] 
        reader:
        - _target_: serotiny.image.io.MonaiBioReader
          dimension_order_out: 'CZYX'

      - _target_: monai.transforms.ToTensord
        keys: ['source', 'target'] 

      - _target_: aics_im2im.utils.MatchHistogramToReference
        keys: ['source']
        reference: '/allen/aics/assay-dev/computational/data/nucleus_tracking/lamin/bf'
        sample_size: 10

      - _target_: monai.transforms.RandAdjustContrastd
        keys: ['source']
        prob: 0.25
        gamma: 0.75

      - _target_: aics_im2im.utils.MeanNormalizeIntensity
        keys: ['source']
        lower_bound: 5
        upper_bound: 12.0

      - _target_: serotiny.image.transforms.RandomMultiScaleCropd
        keys: ['source', 'target']
        patch_shape: ${model.patch_shape}
        patch_per_image: 1
        scales_dict:
          1: ['source', 'target']
      
      - _target_: aics_im2im.utils.ExtractCentroidd
        input_key: 'target'
        output_key: 'CE'

      - _target_: aics_im2im.utils.EmbedSegConcatLabelsd
        input_keys: ['target', 'CE']
        output_key: GT
        

  predict:
    _target_: monai.transforms.Compose
    transforms: 
      - _target_: monai.transforms.LoadImaged
        keys: ['source'] 
        reader:
        - _target_: serotiny.image.io.MonaiBioReader
          dimension_order_out: 'CZYX'

      - _target_: monai.transforms.ToTensord
        keys: ['source'] 

      - _target_: aics_im2im.utils.MeanNormalizeIntensity
        keys: ['source']
        lower_bound: 5
        upper_bound: 12.0
    
      
