_target_: serotiny.datamodules.dataframe.DataframeDatamodule

path: //allen/aics/assay-dev/users/Benji/CurrentProjects/20xBF_to_cellseg/laminseg_separate_interphase_and_mitotic_channel/add_real_images/goldilocks_test/max_projects/pred/gts
cache_dir: //allen/aics/assay-dev/users/Benji/CurrentProjects/20xBF_to_cellseg/laminseg_separate_interphase_and_mitotic_channel/add_real_images/goldilocks_test/max_projects/pred/gts/cache

num_workers: 0
batch_size: 1
pin_memory: True
persistent_workers: False
columns: ['seg', 'raw']

transforms:
  train:
    _target_: monai.transforms.Compose
    transforms: 
      - _target_: monai.transforms.LoadImaged
        keys: ['raw','seg']
        reader:
        - _target_: serotiny.image.io.MonaiBioReader
          dimension_order_out: 'CYX'

      - _target_: monai.transforms.ToTensord
        keys: ['seg', 'raw']  
      - _target_: monai.transforms.NormalizeIntensityd
        keys: ['raw']

      - _target_: serotiny.image.transforms.RandomMultiScaleCropd
        keys: ['seg', 'raw']
        patch_shape: [512, 512]
        patch_per_image: 16
        scales_dict:
          1: ['seg', 'raw']
        selection_fn:
          _target_: serotiny.image.transforms.BrightSampler
          key: 'seg'
          threshold: 0
          base_prob: 0.15

      - _target_: monai.transforms.RandHistogramShiftd
        prob: 0.3
        keys: ['raw']
        num_control_points: [90, 500]

      - _target_: monai.transforms.RandStdShiftIntensityd
        prob: 0.3
        keys: ['raw']
        factors: 0.1 

      - _target_: monai.transforms.RandAdjustContrastd
        prob: 0.3
        keys: ['raw']
        gamma: [0.9, 1.1]

      - _target_: monai.transforms.RandFlipd
        keys: ['seg', 'raw']
        prob: 0.5
        spatial_axis: [1]
      - _target_: monai.transforms.RandFlipd
        keys: ['seg', 'raw']
        prob: 0.5
        spatial_axis: [0]

      - _target_: monai.transforms.RandRotate90d
        keys: ['seg', 'raw']
        prob: 0.5
        spatial_axes: [0, 1]

  test:
    _target_: monai.transforms.Compose
    transforms: 
      - _target_: monai.transforms.LoadImaged
        keys: [ 'raw']
        reader:
        - _target_: serotiny.image.io.MonaiBioReader
          dimension_order_out: 'CYX'
      - _target_: monai.transforms.ToTensord
        keys: ['raw']    
      - _target_: monai.transforms.NormalizeIntensityd
        keys: ['raw']

  valid:
    _target_: monai.transforms.Compose
    transforms: 
      - _target_: monai.transforms.LoadImaged
        keys: ['raw', 'seg']
        reader:
        - _target_: serotiny.image.io.MonaiBioReader
          dimension_order_out: 'CYX'
      - _target_: monai.transforms.ToTensord
        keys: ['seg', 'raw']   
      - _target_: monai.transforms.NormalizeIntensityd
        keys: ['raw']

      - _target_: serotiny.image.transforms.RandomMultiScaleCropd
        keys: ['seg', 'raw']
        patch_shape:  [512, 512]
        patch_per_image: 32
        scales_dict:
          1: ['seg', 'raw']

