_target_: serotiny.datamodules.dataframe.DataframeDatamodule

path: 
cache_dir:

num_workers: 8
batch_size: 3
pin_memory: True
persistent_workers: False
split_column: split
columns: 
  - raw
  - seg 
  - mitotic_mask
  - split

transforms:
  train:
    _target_: monai.transforms.Compose
    transforms: 
      - _target_: monai.transforms.LoadImaged
        keys: [raw]
        reader:
        - _target_: serotiny.image.io.MonaiBioReader
          dimension_order_out: 'CZYX'
          
      - _target_: monai.transforms.LoadImaged
        keys: [seg]
        dtype: short
        reader:
        - _target_: serotiny.image.io.MonaiBioReader
          dimension_order_out: 'CZYX'

      - _target_: monai.transforms.LoadImaged
        keys: [mitotic_mask]
        dtype: short
        reader:
        - _target_: serotiny.image.io.MonaiBioReader
          dimension_order_out: 'CYX'

      - _target_: monai.transforms.ToTensord
        keys: [raw, seg, mitotic_mask]
      - _target_: monai.transforms.NormalizeIntensityd
        keys: 
          - raw
        dtype: float16
      - _target_: monai.transforms.ThresholdIntensityd
        keys: [seg, mitotic_mask]
        threshold: 0.1
        above: False
        cval: 1

      - _target_: serotiny.image.transforms.RandomMultiScaleCropd
        keys: [raw, seg, mitotic_mask]
        patch_shape: ${model.patch_shape}
        patch_per_image: 1
        scales_dict:
          1:  [raw, seg, mitotic_mask]
       

  test:
    _target_: monai.transforms.Compose
    transforms: 
      - _target_: monai.transforms.LoadImaged
        keys:   
          - raw
        reader:
        - _target_: serotiny.image.io.MonaiBioReader
          dimension_order_out: 'CZYX'
      - _target_: monai.transforms.ToTensord
        keys:   
          - raw
      - _target_: monai.transforms.NormalizeIntensityd
        keys:   
          - raw

  valid:
    _target_: monai.transforms.Compose
    transforms: 
      - _target_: monai.transforms.LoadImaged
        keys: [raw, seg]
        dtype: short
        reader:
        - _target_: serotiny.image.io.MonaiBioReader
          dimension_order_out: 'CZYX'

      - _target_: monai.transforms.LoadImaged
        keys: [mitotic_mask]
        dtype: short
        reader:
        - _target_: serotiny.image.io.MonaiBioReader
          dimension_order_out: 'CYX'

      - _target_: monai.transforms.ToTensord
        keys: [raw, seg, mitotic_mask]

      - _target_: monai.transforms.NormalizeIntensityd
        keys: 
          - raw
        dtype: float16
        
      - _target_: monai.transforms.ThresholdIntensityd
        keys: [seg, mitotic_mask]
        threshold: 0.1
        above: False
        cval: 1

      - _target_: serotiny.image.transforms.RandomMultiScaleCropd
        keys: [raw, seg, mitotic_mask]
        patch_shape: ${model.patch_shape}
        patch_per_image: 1
        scales_dict:
          1:  [raw, seg, mitotic_mask]
       

