_target_: serotiny.datamodules.dataframe.DataframeDatamodule

path: 
cache_dir:

num_workers: 0
batch_size: 1
pin_memory: True
persistent_workers: False
columns: ['high_res', 'low_res']

transforms:
  train:
    _target_: monai.transforms.Compose
    transforms: 
      - _target_: monai.transforms.LoadImaged
        keys: ['low_res','high_res']
        reader:
        - _target_: serotiny.image.io.MonaiBioReader
          dimension_order_out: 'CZYX'

      - _target_: monai.transforms.ToTensord
        keys: ['high_res', 'low_res']  
      - _target_: monai.transforms.NormalizeIntensityd
        keys: ['low_res', high_res]

      - _target_: monai.transforms.ScaleIntensityRangePercentilesd
        keys: 'hr_lamin'
        lower: 0.01
        upper: 99.99
        b_min: -1
        b_max: 1

      - _target_: serotiny.image.transforms.RandomMultiScaleCropd
        keys: ['high_res', 'low_res']
        patch_shape: [32, 256, 256]
        patch_per_image: 4
        scales_dict:
          1: ['high_res']
          2: ['low_res']

      - _target_: monai.transforms.RandHistogramShiftd
        prob: 0.3
        keys: ['low_res']
        num_control_points: [90, 500]

      - _target_: monai.transforms.RandStdShiftIntensityd
        prob: 0.3
        keys: ['low_res']
        factors: 0.1 

      - _target_: monai.transforms.RandAdjustContrastd
        prob: 0.3
        keys: ['low_res']
        gamma: [0.9, 1.1]

      - _target_: monai.transforms.RandFlipd
        keys: ['high_res', 'low_res']
        prob: 0.5
        spatial_axis: [1]
      - _target_: monai.transforms.RandFlipd
        keys: ['high_res', 'low_res']
        prob: 0.5
        spatial_axis: [0]

      - _target_: monai.transforms.RandRotate90d
        keys: ['high_res', 'low_res']
        prob: 0.5
        spatial_axes: [0, 1]

  test:
    _target_: monai.transforms.Compose
    transforms: 
      - _target_: monai.transforms.LoadImaged
        keys: [ 'low_res']
        reader:
        - _target_: serotiny.image.io.MonaiBioReader
          dimension_order_out: 'CYX'
      - _target_: monai.transforms.ToTensord
        keys: ['low_res']    
      - _target_: monai.transforms.NormalizeIntensityd
        keys: ['low_res']

  valid:
    _target_: monai.transforms.Compose
    transforms: 
      - _target_: monai.transforms.LoadImaged
        keys: ['low_res', 'high_res']
        reader:
        - _target_: serotiny.image.io.MonaiBioReader
          dimension_order_out: 'CZYX'
      - _target_: monai.transforms.ToTensord
        keys: ['high_res', 'low_res']   
      - _target_: monai.transforms.NormalizeIntensityd
        keys: ['low_res']

      - _target_: serotiny.image.transforms.RandomMultiScaleCropd
        keys: ['high_res', 'low_res']
        patch_shape:  [32, 512, 512]
        patch_per_image: 8
        scales_dict:
          1: ['high_res']
          2: ['low_res']

