_target_: cyto_dl.models.basic_model.BasicModel

x_label: pcloud

network:
  _target_: cyto_dl.nn.point_cloud.Point_M2AE
  drop_path_rate: 0.1
  num_heads: 6
  decoder_up_blocks: [1,1]
  decoder_dims: [384, 192]
  decoder_depths: [1,1]
  group_sizes: [18,8,8]
  num_groups: [512, 256, 64]
  mask_ratio: 0.8
  encoder_depths: [5,5,5]
  encoder_dims: [96, 192, 384]
  local_radius: [0.32, 0.64, 1.28]

loss:
  _target_: cyto_dl.nn.losses.ChamferLoss

optimizer:
  _partial_: true
  _target_: torch.optim.adam.Adam
  lr: 0.0002

