_target_: cyto_dl.models.im2im.MultiTaskIm2Im

save_images_every_n_epochs: 50
save_dir: ${paths.output_dir}

x_key: ${source_col}
# patch_shape:

backbone:
  _target_: monai.networks.nets.DynUNet
  spatial_dims: ${spatial_dims}
  in_channels: ${raw_im_channels}
  out_channels: 1
  strides: [1, 2, 2, 2]
  kernel_size: [3, 3, 3, 3]
  upsample_kernel_size: [2, 2, 2]
  dropout: 0.0
  res_block: True

task_heads: ${kv_to_dict:${model._aux._tasks}}

optimizer:
  generator:
    _partial_: True
    _target_: torch.optim.Adam
    lr: 0.0001
    weight_decay: 0.0001

lr_scheduler:
  generator:
    _partial_: True
    _target_: torch.optim.lr_scheduler.ExponentialLR
    gamma: 0.995

inference_args:
  sw_batch_size: 1
  roi_size: ${data._aux.patch_shape}

_aux:
  _tasks:
    - - ${target_col}
      - _target_: cyto_dl.nn.BaseHead
        loss:
          _target_: monai.losses.GeneralizedDiceFocalLoss  ##Main loss
          sigmoid: True
        postprocess:
          input:
            _target_: cyto_dl.models.im2im.utils.postprocessing.ActThreshLabel
            rescale_dtype: numpy.uint8
          prediction:
            _target_: cyto_dl.models.im2im.utils.postprocessing.ActThreshLabel
            activation:
              _target_: torch.nn.Sigmoid
            rescale_dtype: numpy.uint8
