_target_: aics_im2im.models.vae.PointCloudVAE

x_label: pcloud
# id_label: cell_id

latent_dim: 128
num_points: 4096
hidden_encoder_features: [64, 128, 256, 512]
hidden_decoder_dim: 512
k: 20

mode: scalar
equivariant: false
include_cross: false
include_coords: true

beta: 1.0
embedding_prior: "identity"

eps: 1e-6
