_target_: aics_im2im.models.vae.PointCloudVAE

x_label: pcloud
# id_label: cell_id

num_features: 20
k: 20
hidden_dim: 64
hidden_conv2d_channels: [64, 64, 64, 64]
hidden_conv1d_channels: [512, 512]


mode: scalar
scalar_inds: 
get_rotation: false
include_cross: false
include_coords: true
symmetry_breaking_axis: 
generate_grid_feats: False

decoder_type: 'foldingnet'
shape: "plane"

loss_type: 'chamfer'

beta: 1.0
embedding_prior: "gaussian"

eps: 1e-6

optimizer:
  _partial_: true
  _target_: torch.optim.adam.Adam
  lr: 0.0002
