_target_: aics_im2im.models.vae.PointCloudVAE

x_label: pcloud
# id_label: cell_id

latent_dim: 10
num_points: 256
# hidden_encoder_features: [64, 64, 128, 256, 512]
hidden_dim: 64
hidden_decoder_dim: 512
k: 20

mode: scalar
get_rotation: false
include_cross: false
include_coords: true
shape: "gaussian"

beta: 1.0
embedding_prior: "identity"

eps: 1e-6

optimizer:
  _partial_: true
  _target_: torch.optim.adam.Adam
  lr: 0.0002
