_target_: aics_ls.models.vae.PointCloudVAE

x_label: pcloud
id_label: cell_id

latent_dim:
num_points:
hidden_encoder_features: [64, 128, 256, 512]
hidden_decoder_dim: 512
k: 20

mode: scalar
equivariant: true
include_cross: false
include_coords: false

beta: 1.0
embedding_prior: str = "gaussian"

eps: 1e-6
