_target_: aics_ls.models.vae.PointCloudVAE

x_label: pcloud
id_label: cell_id

latent_dim:
num_points:
hidden_encoder_features: [64, 128, 256, 512]
hidden_decoder_dim: 512
k: 20

mode: vector
equivariant: true
include_cross: true
include_coords: true

beta: 1.0
embedding_prior: str = "identity"

eps: 1e-6
