_target_: aics_im2im.models.vae.ImageKoopmanAE

latent_dim: 128
x_label: image
in_channels: 1

channels: [2, 4, 8, 16, 32]
strides: [2, 2, 2, 2, 2]

rank: 0 # 0 means full rank

spatial_dims: 3
kernel_size: 3
up_kernel_size: 3

act: "MISH"
norm: "INSTANCE"
