_target_: cyto_dl.nn.losses.SDFGridLoss
n_samples: 2500
max_x: 1.9 # calculated based on max size of pcna resize pooint cloud
max_y: 1.7
max_z: 0.43
grid_size: 50000
p_norm: 1
replace: False
mean: true
fix_grid: True
convex_hull: True