name: Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install numpy
          pip install -r requirements/docs-requirements.txt
          pip install .
      - name: Generate Docs
        run: |
          make gen-docs
          touch docs/_build/html/.nojekyll
      - name: Publish Docs
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: main # The branch the action should deploy from.
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/_build/html/ # The folder the action should deploy.
