name: create PR from public

on:
  workflow_dispatch:
    inputs:
      public_pr_number:
        required: true

jobs:
  make-pr:
    runs-on: ubuntu-latest

    steps:
      - name: checkout private repo
        uses: actions/checkout@v3

      - name: Get PR patch
        run: |
          PR_NUMBER=${{ github.event.inputs.public_pr_number }}
          OWNER=AllenCell
          REPO=cyto-dl

          curl -o ../public-pr.patch \
              -L \
              -H "Accept: application/vnd.github.patch" \
              -H "Authorization: Bearer ${{ secrets.CYTO_DL_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/repos/$OWNER/$REPO/pulls/$PR_NUMBER"

      - name: Run a multi-line script
        run: git apply --reject --ignore-space-change ../public-pr.patch

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.AUTO_PR_TOKEN }}
          branch: pr-from-public-repo/${{ github.event.inputs.public_pr_number}}
          commit-message: |
            Applying changes from https://github.com/AllenCell/cyto-dl/pull/${{ github.event.inputs.public_pr_number }}
