name: Make requirements files

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "pyproject.toml"

jobs:
  check-lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up UV
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5.4.2
        with:
          python-version-file: "pyproject.toml"
          version: "0.6.14"
      - name: Check if lockfile is up to date
        shell: bash
        run: |
          set +e
          test -f uv.lock && uv lock --check
          echo "up-to-date=$?" >> $GITHUB_OUTPUT

  make-requirements:
    runs-on: ubuntu-latest
    needs: check-lockfile
    if: ${{ needs.check-lockfile.outputs.up-to-date == 0 }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up UV
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5.4.2
        with:
          python-version-file: "pyproject.toml"
          version: "0.6.14"
      - name: Generate lockfile and requirements files
        shell: bash
        run: |
          rm -r requirements/
          make sync-reqs-files
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 # v5.2.0
