name: Make requirements files

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "pyproject.toml"

jobs:
  make-requirements:
    steps:
      - uses: actions/checkout@v3
      - name: Set up UV
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86  # v5.4.2
        with:
          python-version-file: "pyproject.toml"

      - name: 
        shell: bash
        run: |
          rm -r requirements/*
          make sync-reqs-files

      - name: Upload uv.lock
        uses: actions/upload-artifact@v4
        with:
          name: uv.lock
          path: uv.lock

      - name: Upload requirements files
        uses: actions/upload-artifact@v4
        with:
          name: requirements
          path: requirements

  open-PR:
    needs: [make-requirements]
    steps:
      - uses: actions/checkout@v3
      - name: Download uv.lock
        uses: actions/download-artifact@v4
        with:
          name: uv.lock
          path: uv.lock
      - name: Download requirements files
        uses: actions/download-artifact@v4
        with:
          name: requirements
          path: requirements

      - name: Get timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +'%Y-%m-%d_%H-%M')"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          base: main
          title: admin/requirements-update_${{ steps.timestamp.outputs.timestamp }}
          body: Updating lock files and requirements
          branch: admin/requirements-update_${{ steps.timestamp.outputs.timestamp }}
          commit-message: Updating lock files and requirements
          delete-branch: true
