---
name: publish
on:
  pull_request:
    types: [closed]
    branches: [main]
jobs:
  publish:
    # only publish when the PR is a version bump PR and the pr is merged to main
    if: github.event.pull_request.title == 'admin/version-bump' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v2
        with:
          python-version: "3.10"

      - name: Build package
        run: pdm build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
