name: dispatch public workflow

on:
  pull_request:
    branches: [main]
    types: [closed]
    paths-ignore:
      - ".github/**"

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger public workflow
        if: |
          github.event_name == 'pull_request' &&
          github.event.action == 'closed' &&
          github.event.pull_request.merged == true &&
          !contains(github.head_ref, 'pr-from-public-repo')

        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.WORKFLOW_TRIGGER_TOKEN }}
          script: |
            const result = await github.rest.actions.createWorkflowDispatch({
              owner: 'AllenCell',
              repo: 'cyto-dl',
              workflow_id: 'create-pr-from-private.yml',
              ref: 'main',
              inputs: {
                private_pr_number: '${{ github.event.pull_request.number }}'
              }
            })
            console.log(result)
